/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArmazenamentoRouteImport } from './routes/armazenamento'
import { Route as ClpsRouteImport } from './routes/clps'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as UsuariosRouteImport } from './routes/usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmazenamentoRoute = ArmazenamentoRouteImport.update({
  id: '/armazenamento',
  path: '/armazenamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ClpsRoute = ClpsRouteImport.update({
  id: '/clps',
  path: '/clps',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/armazenamento': typeof ArmazenamentoRoute
  '/clps': typeof ClpsRoute
  '/tags': typeof TagsRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/armazenamento': typeof ArmazenamentoRoute
  '/clps': typeof ClpsRoute
  '/tags': typeof TagsRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/armazenamento': typeof ArmazenamentoRoute
  '/clps': typeof ClpsRoute
  '/tags': typeof TagsRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/armazenamento' | '/clps' | '/tags' | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/armazenamento' | '/clps' | '/tags' | '/usuarios'
  id: '__root__' | '/' | '/armazenamento' | '/clps' | '/tags' | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArmazenamentoRoute: typeof ArmazenamentoRoute
  ClpsRoute: typeof ClpsRoute
  TagsRoute: typeof TagsRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/armazenamento': {
      id: '/armazenamento'
      path: '/armazenamento'
      fullPath: '/armazenamento'
      preLoaderRoute: typeof ArmazenamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clps': {
      id: '/clps'
      path: '/clps'
      fullPath: '/clps'
      preLoaderRoute: typeof ClpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArmazenamentoRoute: ArmazenamentoRoute,
  ClpsRoute: ClpsRoute,
  TagsRoute: TagsRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
